project:
  type: website
  output-dir: docs

website:
  title: "Nathan Wu"
  twitter-card: true
  site-url: https://nathanw23.github.io
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
  page-footer:
    left: "This website was built with [Quarto](https://www.quarto.org)"
    right: "Â© 2023 Nathan Wu"

format:
  html:
    light: minty
    css: styles.css
    toc: true
